logo: /assets/images/logo.png
description: Documentation
theme: jekyll-theme-minimal
baseurl: /manhattan
url: http://dreamworksanimation.github.io/
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" 
    values:
      layout: "default"
collections_dir: docs
collections:
  light-filters:
    output: true
    order:
      - Barn-Door-Light-Filter.md
      - Cookie-Light-Filter.md
      - Decay-Light-Filter.md
