logo: /assets/images/logo.png
description: Documentation
theme: jekyll-theme-minimal
baseurl: /manhattan
url: http://dreamworksanimation.github.io/
collections_dir: docs

collections:
  light-filters:
    permalink: docs/:collection/:name
    output: true
  lights:
    permalink: docs/:collection/:name
    output: true
    
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" 
    values:
      layout: "default"
      
