logo: /assets/images/logo.png
description: Documentation
theme: jekyll-theme-minimal
baseurl: /manhattan
url: http://dreamworksanimation.github.io/
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" 
    values:
      layout: "default"
